version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'digital_library'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: digital_library_api
    build:
      context: ./backend
      dockerfile: DigitalLibrary.API/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=digital_library;Username=postgres;Password=password;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  postgres_data: